'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports OmahaMTG.Challenge.DomainModel
Partial Public Class CodeChallengeEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CodeChallengeEntities")
    End Sub

	    Public Sub New(connectionString as string)
        MyBase.New(connectionString)
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property CodeChallenges() As DbSet(Of CodeChallenge)
    Public Property CodeChallenge_Announcement() As DbSet(Of CodeChallenge_Announcement)
    Public Property CodeChallenge_Assembly() As DbSet(Of CodeChallenge_Assembly)
    Public Property CodeChallenge_Config() As DbSet(Of CodeChallenge_Config)
    Public Property CodeChallenge_DeveloperAssembly() As DbSet(Of CodeChallenge_DeveloperAssembly)
    Public Property CodeChallenge_Entry() As DbSet(Of CodeChallenge_Entry)
    Public Property CodeChallenge_Entry_Result() As DbSet(Of CodeChallenge_Entry_Result)
    Public Property CodeChallenge_Sponsor() As DbSet(Of CodeChallenge_Sponsor)
    Public Property vw_codechallenge_entry_challenge_user() As DbSet(Of vw_codechallenge_entry_challenge_user)
    Public Property vw_codechallenge_secure() As DbSet(Of vw_codechallenge_secure)
    Public Property vwCodeChallengeEntryHistories() As DbSet(Of vwCodeChallengeEntryHistory)

End Class
