'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CodeChallenge_Sponsor
    Public Property id As Integer
    Public Property Name As String
    Public Property Description As String

    Public Overridable Property CodeChallenges As ICollection(Of CodeChallenge) = New HashSet(Of CodeChallenge)

End Class
