'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CodeChallenge_DeveloperAssembly
    Public Property id As Integer
    Public Property codechallenge_id As Integer
    Public Property assembly_fullname As String
    Public Property [assembly] As Byte()
    Public Property NumberOfDownloads As Nullable(Of Integer)

    Public Overridable Property CodeChallenge As CodeChallenge

End Class
