'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CodeChallenge
    Public Property id As Integer
    Public Property ChallengeName As String
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property SampleProjectFilename As String
    Public Property SampleProject As Byte()
    Public Property DocumentationFilename As String
    Public Property Documentation As Byte()
    Public Property Instructions As String
    Public Property ExecutorAssembly As Byte()
    Public Property ExecutorAssemblyFullName As String
    Public Property ExecutionCommonAssembly As Byte()
    Public Property ExecutionCommonAssemblyFullName As String
    Public Property MaximumRunningSeconds As Integer
    Public Property MaximumMemoryUsageBytes As Decimal
    Public Property CodeChallenge_Sponsor_id As Nullable(Of Integer)
    Public Property SampleDownloads As Nullable(Of Integer)
    Public Property DocumentationDownloads As Nullable(Of Integer)
    Public Property IsHidden As Nullable(Of Boolean)
    Public Property TotalEntries As Integer

    Public Overridable Property CodeChallenge_Sponsor As CodeChallenge_Sponsor
    Public Overridable Property CodeChallenge_DeveloperAssembly As ICollection(Of CodeChallenge_DeveloperAssembly) = New HashSet(Of CodeChallenge_DeveloperAssembly)
    Public Overridable Property CodeChallenge_Entry As ICollection(Of CodeChallenge_Entry) = New HashSet(Of CodeChallenge_Entry)

End Class
