'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CodeChallenge_Assembly
    Public Property id As Integer
    Public Property [assembly] As Byte()
    Public Property AssemblyFullName As String
    Public Property Trusted As Boolean

End Class
