'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_codechallenge_entry_challenge_user
    Public Property ChallengeName As String
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property Instructions As String
    Public Property MaximumRunningSeconds As Integer
    Public Property MaximumMemoryUsageBytes As Decimal
    Public Property id As Integer
    Public Property CodeChallenge_Id As Integer
    Public Property AuthorUserId As System.Guid
    Public Property AssemblyFullName As String
    Public Property DateAdded As Date
    Public Property DateRan As Nullable(Of Date)
    Public Property TotalExecutionTime As Nullable(Of Integer)
    Public Property FinalScore As Nullable(Of Integer)
    Public Property UserName As String
    Public Property UserId As System.Guid
    Public Property TypeName As String
    Public Property ExecutorAssemblyFullName As String
    Public Property ExecutionCommonAssemblyFullName As String
    Public Property Expr1 As Integer
    Public Property DocumentationFilename As String
    Public Property SampleProjectFilename As String
    Public Property IsHidden As Nullable(Of Boolean)

End Class
