'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_codechallenge_secure
    Public Property id As Integer
    Public Property ChallengeName As String
    Public Property StartDate As Date
    Public Property EndDate As Date
    Public Property Instructions As String
    Public Property ExecutorAssemblyFullName As String
    Public Property ExecutionCommonAssemblyFullName As String
    Public Property MaximumRunningSeconds As Integer
    Public Property MaximumMemoryUsageBytes As Decimal
    Public Property SampleProjectFilename As String
    Public Property DocumentationFilename As String
    Public Property SponsorName As String
    Public Property SponsorDescription As String
    Public Property SampleDownloads As Nullable(Of Integer)
    Public Property DocumentationDownloads As Nullable(Of Integer)
    Public Property IsHidden As Nullable(Of Boolean)

End Class
