'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18034
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AuthenticationService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="QueryResult", [Namespace]:="DomainServices"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.QueryResultOfUser))>  _
    Partial Public Class QueryResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalCountField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TotalCount() As Integer
            Get
                Return Me.TotalCountField
            End Get
            Set
                If (Me.TotalCountField.Equals(value) <> true) Then
                    Me.TotalCountField = value
                    Me.RaisePropertyChanged("TotalCount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="QueryResultOfUser", [Namespace]:="DomainServices"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.User)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.User())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(String())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Object())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, Integer()))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Integer())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, Object()))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.QueryResult)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.DomainServiceFault)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.ValidationResultInfo())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.ValidationResultInfo)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.ChangeSetEntry())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.ChangeSetEntry)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.DomainOperation))>  _
    Partial Public Class QueryResultOfUser
        Inherits AuthenticationService.QueryResult
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IncludedResultsField() As Object
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RootResultsField() As AuthenticationService.User
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IncludedResults() As Object()
            Get
                Return Me.IncludedResultsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IncludedResultsField, value) <> true) Then
                    Me.IncludedResultsField = value
                    Me.RaisePropertyChanged("IncludedResults")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property RootResults() As AuthenticationService.User()
            Get
                Return Me.RootResultsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RootResultsField, value) <> true) Then
                    Me.RootResultsField = value
                    Me.RaisePropertyChanged("RootResults")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="User", [Namespace]:="http://schemas.datacontract.org/2004/07/SilverlightUI.Web"),  _
     System.SerializableAttribute()>  _
    Partial Public Class User
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisplayNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FriendlyNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RolesField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIDField As System.Guid
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DisplayName() As String
            Get
                Return Me.DisplayNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayNameField, value) <> true) Then
                    Me.DisplayNameField = value
                    Me.RaisePropertyChanged("DisplayName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FriendlyName() As String
            Get
                Return Me.FriendlyNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FriendlyNameField, value) <> true) Then
                    Me.FriendlyNameField = value
                    Me.RaisePropertyChanged("FriendlyName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Roles() As String()
            Get
                Return Me.RolesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RolesField, value) <> true) Then
                    Me.RolesField = value
                    Me.RaisePropertyChanged("Roles")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserID() As System.Guid
            Get
                Return Me.UserIDField
            End Get
            Set
                If (Me.UserIDField.Equals(value) <> true) Then
                    Me.UserIDField = value
                    Me.RaisePropertyChanged("UserID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DomainServiceFault", [Namespace]:="DomainServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DomainServiceFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsDomainExceptionField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationErrorsField() As AuthenticationService.ValidationResultInfo
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StackTraceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Me.ErrorCodeField.Equals(value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsDomainException() As Boolean
            Get
                Return Me.IsDomainExceptionField
            End Get
            Set
                If (Me.IsDomainExceptionField.Equals(value) <> true) Then
                    Me.IsDomainExceptionField = value
                    Me.RaisePropertyChanged("IsDomainException")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OperationErrors() As AuthenticationService.ValidationResultInfo()
            Get
                Return Me.OperationErrorsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperationErrorsField, value) <> true) Then
                    Me.OperationErrorsField = value
                    Me.RaisePropertyChanged("OperationErrors")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property StackTrace() As String
            Get
                Return Me.StackTraceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StackTraceField, value) <> true) Then
                    Me.StackTraceField = value
                    Me.RaisePropertyChanged("StackTrace")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ValidationResultInfo", [Namespace]:="DomainServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ValidationResultInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceMemberNamesField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StackTraceField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ErrorCode() As Integer
            Get
                Return Me.ErrorCodeField
            End Get
            Set
                If (Me.ErrorCodeField.Equals(value) <> true) Then
                    Me.ErrorCodeField = value
                    Me.RaisePropertyChanged("ErrorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property SourceMemberNames() As String()
            Get
                Return Me.SourceMemberNamesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceMemberNamesField, value) <> true) Then
                    Me.SourceMemberNamesField = value
                    Me.RaisePropertyChanged("SourceMemberNames")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property StackTrace() As String
            Get
                Return Me.StackTraceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StackTraceField, value) <> true) Then
                    Me.StackTraceField = value
                    Me.RaisePropertyChanged("StackTrace")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ChangeSetEntry", [Namespace]:="DomainServices"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.User)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.User())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(String())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Object())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, Integer()))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Integer())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Collections.Generic.Dictionary(Of String, Object()))),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.QueryResultOfUser)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.QueryResult)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.DomainServiceFault)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.ValidationResultInfo())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.ValidationResultInfo)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.ChangeSetEntry())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(AuthenticationService.DomainOperation))>  _
    Partial Public Class ChangeSetEntry
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssociationsField As System.Collections.Generic.Dictionary(Of String, Integer())
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConflictMembersField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EntityField As Object
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EntityActionsField As System.Collections.Generic.Dictionary(Of String, Object())
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HasMemberChangesField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsDeleteConflictField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationField As AuthenticationService.DomainOperation
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginalAssociationsField As System.Collections.Generic.Dictionary(Of String, Integer())
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OriginalEntityField As Object
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StoreEntityField As Object
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ValidationErrorsField() As AuthenticationService.ValidationResultInfo
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Associations() As System.Collections.Generic.Dictionary(Of String, Integer())
            Get
                Return Me.AssociationsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AssociationsField, value) <> true) Then
                    Me.AssociationsField = value
                    Me.RaisePropertyChanged("Associations")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ConflictMembers() As String()
            Get
                Return Me.ConflictMembersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ConflictMembersField, value) <> true) Then
                    Me.ConflictMembersField = value
                    Me.RaisePropertyChanged("ConflictMembers")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Entity() As Object
            Get
                Return Me.EntityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntityField, value) <> true) Then
                    Me.EntityField = value
                    Me.RaisePropertyChanged("Entity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EntityActions() As System.Collections.Generic.Dictionary(Of String, Object())
            Get
                Return Me.EntityActionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntityActionsField, value) <> true) Then
                    Me.EntityActionsField = value
                    Me.RaisePropertyChanged("EntityActions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HasMemberChanges() As Boolean
            Get
                Return Me.HasMemberChangesField
            End Get
            Set
                If (Me.HasMemberChangesField.Equals(value) <> true) Then
                    Me.HasMemberChangesField = value
                    Me.RaisePropertyChanged("HasMemberChanges")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IsDeleteConflict() As Boolean
            Get
                Return Me.IsDeleteConflictField
            End Get
            Set
                If (Me.IsDeleteConflictField.Equals(value) <> true) Then
                    Me.IsDeleteConflictField = value
                    Me.RaisePropertyChanged("IsDeleteConflict")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Operation() As AuthenticationService.DomainOperation
            Get
                Return Me.OperationField
            End Get
            Set
                If (Me.OperationField.Equals(value) <> true) Then
                    Me.OperationField = value
                    Me.RaisePropertyChanged("Operation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OriginalAssociations() As System.Collections.Generic.Dictionary(Of String, Integer())
            Get
                Return Me.OriginalAssociationsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginalAssociationsField, value) <> true) Then
                    Me.OriginalAssociationsField = value
                    Me.RaisePropertyChanged("OriginalAssociations")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property OriginalEntity() As Object
            Get
                Return Me.OriginalEntityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OriginalEntityField, value) <> true) Then
                    Me.OriginalEntityField = value
                    Me.RaisePropertyChanged("OriginalEntity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property StoreEntity() As Object
            Get
                Return Me.StoreEntityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StoreEntityField, value) <> true) Then
                    Me.StoreEntityField = value
                    Me.RaisePropertyChanged("StoreEntity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ValidationErrors() As AuthenticationService.ValidationResultInfo()
            Get
                Return Me.ValidationErrorsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValidationErrorsField, value) <> true) Then
                    Me.ValidationErrorsField = value
                    Me.RaisePropertyChanged("ValidationErrors")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DomainOperation", [Namespace]:="DomainServices")>  _
    Public Enum DomainOperation As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Query = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Insert = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Update = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Delete = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Custom = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Invoke = 6
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AuthenticationService.AuthenticationServicesoap")>  _
    Public Interface AuthenticationServicesoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AuthenticationServicesoap/Login", ReplyAction:="http://tempuri.org/AuthenticationServicesoap/LoginResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AuthenticationService.DomainServiceFault), Action:="http://tempuri.org/AuthenticationServicesoap/LoginDomainServiceFault", Name:="DomainServiceFault", [Namespace]:="DomainServices")>  _
        Function Login(ByVal userName As String, ByVal password As String, ByVal isPersistent As Boolean, ByVal customData As String) As AuthenticationService.QueryResultOfUser
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AuthenticationServicesoap/Logout", ReplyAction:="http://tempuri.org/AuthenticationServicesoap/LogoutResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AuthenticationService.DomainServiceFault), Action:="http://tempuri.org/AuthenticationServicesoap/LogoutDomainServiceFault", Name:="DomainServiceFault", [Namespace]:="DomainServices")>  _
        Function Logout() As AuthenticationService.QueryResultOfUser
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AuthenticationServicesoap/GetUser", ReplyAction:="http://tempuri.org/AuthenticationServicesoap/GetUserResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AuthenticationService.DomainServiceFault), Action:="http://tempuri.org/AuthenticationServicesoap/GetUserDomainServiceFault", Name:="DomainServiceFault", [Namespace]:="DomainServices")>  _
        Function GetUser() As AuthenticationService.QueryResultOfUser
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AuthenticationServicesoap/SubmitChanges", ReplyAction:="http://tempuri.org/AuthenticationServicesoap/SubmitChangesResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(AuthenticationService.DomainServiceFault), Action:="http://tempuri.org/AuthenticationServicesoap/SubmitChangesDomainServiceFault", Name:="DomainServiceFault", [Namespace]:="DomainServices")>  _
        Function SubmitChanges(ByVal changeSet() As AuthenticationService.ChangeSetEntry) As AuthenticationService.ChangeSetEntry()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AuthenticationServicesoapChannel
        Inherits AuthenticationService.AuthenticationServicesoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AuthenticationServicesoapClient
        Inherits System.ServiceModel.ClientBase(Of AuthenticationService.AuthenticationServicesoap)
        Implements AuthenticationService.AuthenticationServicesoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Login(ByVal userName As String, ByVal password As String, ByVal isPersistent As Boolean, ByVal customData As String) As AuthenticationService.QueryResultOfUser Implements AuthenticationService.AuthenticationServicesoap.Login
            Return MyBase.Channel.Login(userName, password, isPersistent, customData)
        End Function
        
        Public Function Logout() As AuthenticationService.QueryResultOfUser Implements AuthenticationService.AuthenticationServicesoap.Logout
            Return MyBase.Channel.Logout
        End Function
        
        Public Function GetUser() As AuthenticationService.QueryResultOfUser Implements AuthenticationService.AuthenticationServicesoap.GetUser
            Return MyBase.Channel.GetUser
        End Function
        
        Public Function SubmitChanges(ByVal changeSet() As AuthenticationService.ChangeSetEntry) As AuthenticationService.ChangeSetEntry() Implements AuthenticationService.AuthenticationServicesoap.SubmitChanges
            Return MyBase.Channel.SubmitChanges(changeSet)
        End Function
    End Class
End Namespace
